export const DDP_CONFIG = {
  ENDPOINT: 'wss://ws.btsbots.com/websocket',
  MAX_SUBSCRIPTION_POOL_SIZE: 25,
  AUTO_RECONNECT_INTERVAL: 3000,
  AUTH_TOKEN_KEY: 'btsbots_login_token',
  APP_MODE_KEY: 'btsbots_app_mode',
  
  COLLECTIONS: {
    GLOBAL: 'global',
    GLOBAL_PROPERTIES: 'global_properties',
    BALANCE: 'balance',
    ORDER: 'order',
    ACCOUNT: 'account',
    ASSET: 'asset',
    TRANSFER: 'transfer',
    MEMO: 'memo',
    FILL_ORDER: 'fill_order',
    ORDER_HISTORY: 'order_history',
    PRICE: 'price',
    VOLUME_ASSET: 'volume_a_1',
    VOLUME_MARKET: 'volume_m_1',
    PROFIT_USER: 'vb_u_1',
    PROXY_SIGN_REQUESTS: 'proxy_sign_requests',
    LOGIN_REQUESTS: 'login_requests',
    USER_ASSET_SETTINGS: 'user_asset_settings',
    TRUST_ASSET: 'trust_asset',
    WALLET_PAYMENT_METADATA: 'wallet_payment_metadata',
    USERS: 'users',
  },

  PUBLICATIONS: {
    TRUST_ASSETS: 'trustAssets',
    MY_ASSET_SETTINGS: 'myAssetSettings',
    MY_PAYMENT_METADATA: 'myPaymentMetadata',
    ALL_PENDING_SIGN_REQUESTS: 'allPendingSignRequests',
    CHAIN_GLOBAL_PROPERTIES: 'chainGlobalProperties',
    CHAIN_BLOCK_HEAD_STREAM: 'chainBlockHeadStream',
    ORDER_BOOK: 'orderBook',
    TRANSFER: 'transfer',
    FILL_ORDER: 'fillOrder',
    ORDER_HISTORY: 'orderHistory',
    HOME_PAGE: 'homePage',
    MARKET_PAGE: 'marketPage',
    USER_PAGE: 'userPage',
    ASSET_PAGE: 'assetPage',
    LOGIN_BALANCE: 'loginBalance',
  },

  METHODS: {
    REQUEST_PROXY_SIGN: 'requestProxySignGoods',
    SUBMIT_OAUTH_AUTHORIZATION: 'submitOAuthAuthorization',
    GET_MARKET_SUMMARY: 'getMarketSummary',
    GET_RANKINGS: 'getRankings',
    GET_ASSET_RANKINGS: 'getAssetRankings',
    TOGGLE_ASSET_VISIBILITY: 'toggleAssetVisibility',
    ADD_FAVORITE: 'addFavoriteAsync',
    REMOVE_FAVORITE: 'removeFavoriteAsync',
  }
} as const;
