export const DDP_CONFIG = {
  ENDPOINT: 'wss://ws.btsbots.com/websocket',
  MAX_SUBSCRIPTION_POOL_SIZE: 25,
  AUTO_RECONNECT_INTERVAL: 3000,
  AUTH_TOKEN_KEY: 'btsbots_login_token',
  APP_MODE_KEY: 'btsbots_app_mode',
  
  COLLECTIONS: {
    GLOBAL: 'global',
    GLOBAL_PROPERTIES: 'global_properties',
    BALANCE: 'balance',
    ORDER: 'order',
    ACCOUNT: 'account',
    ASSET: 'asset',
    TRANSFER: 'transfer',
    MEMO: 'memo',
    FILL_ORDER: 'fill_order',
    ORDER_HISTORY: 'order_history',
    PRICE: 'price',
    VOLUME_ASSET: 'volume_a_1',
    VOLUME_MARKET: 'volume_m_1',
    PROFIT_USER: 'vb_u_1',
    PROXY_SIGN_REQUESTS: 'proxy_sign_requests',
    LOGIN_REQUESTS: 'login_requests',
    WALLET_PAYMENT_METADATA: 'wallet_payment_metadata',
    USERS: 'users',
    VESTING: 'vesting',
    VESTING_WITHDRAW: 'vesting_withdraw',
    INVITATIONS: 'invitations',
  },

  PUBLICATIONS: {
    MY_PAYMENT_METADATA: 'myPaymentMetadata',
    ALL_PENDING_SIGN_REQUESTS: 'allPendingSignRequests',
    CHAIN_GLOBAL_PROPERTIES: 'chainGlobalProperties',
    CHAIN_BLOCK_HEAD_STREAM: 'chainBlockHeadStream',
    ORDER_BOOK: 'orderBook',
    TRANSFER: 'transfer',
    FILL_ORDER: 'fillOrder',
    ORDER_HISTORY: 'orderHistory',
    BALANCE: 'balance',
    PRICE: 'price',
    VESTING: 'vesting',
    VESTING_WITHDRAW: 'vesting_withdraw',
  },

  METHODS: {
    REQUEST_PROXY_SIGN: 'requestProxySignGoods',
    SUBMIT_OAUTH_AUTHORIZATION: 'submitOAuthAuthorization',
    GET_MARKET_SUMMARY: 'getMarketSummary',
    GET_RANKINGS: 'getRankings',
    GET_ASSET_RANKINGS: 'getAssetRankings',
    GET_TRUST_ASSETS: 'getTrustAssets',
    GET_MY_ASSET_SETTINGS: 'getMyAssetSettings',
    SET_ASSET_VISIBILITY: 'setAssetVisibility',
    TOGGLE_ACCOUNT_BLACKLIST: 'toggleAccountBlacklist',
    ADD_FAVORITE: 'addFavoriteAsync',
    REMOVE_FAVORITE: 'removeFavoriteAsync',
    GENERATE_INVITATION: 'generateInvitation',
    LIST_INVITATIONS: 'listInvitations',
    DELETE_INVITATION: 'deleteInvitation',
    GET_ACCOUNT_BY_SYMBOL: 'get_account_document_by_symbol',
  }
} as const;